#1.COMPILACION

#DEFINE LA IMAGE BASE
#DESCARGA UNA COMPUTADORA VIRTUAL QUE YA VENGA CON EL SDK DE .NET8.0 PREINSTALADO
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
#CREA UNA CARPETA SRC DENTRO DEL CONTENEDOR Y NOS METE DENTRO DE ELLA.
#LO QUE VENGA DESPUES SE EJECUTARA DENTRO DE LA CARPETA
WORKDIR /src

#COPIA EL PROYECTO DE LA PC AL CONTENEDOR DESTINO
COPY ["DevOpsDemo.csproj", "./"]
#DESCARGA PAQUETES NuGet.HACERLO ANTES DE COPIAR TODO EL CODIGO ALMACENA EN CACHE LAS DEPENDENCIAS.
#SI EL CODIGO CAMBIA PERO NO SE AGREGAN LIBRERIAS.DOCKER SE SALTA ESTE PASO
RUN dotnet restore

#COPIA EL RESTO DE LOS ARCHIVOS
COPY . . 
#COMPILA LA APP EN RELEASE Y GUARDA EL RESULTADO LISTO PARA PRODUCCION, GUARDA EN CARPETA PUBLISH
RUN dotnet publish -c Release -o /app/publish 

#2.EJECUCION
#AL USAR ASPNET:8.0 NO CONTIENE EL COMPILADOR SDK SOLO EL ENTORNO DE EJECUCION (RUNTIME).PESA MUCHO MENOS QUE EL SDK
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

#VAMOS A LA ETAPA ANTERIOR(BUILD) Y BUSCAMOS LA CARPETA /APP/PUBLISH Y PEGAMOS AQUI
COPY --from=build /app/publish .
#TODA LA BASURA DEL CODIGO FUENTE Y COMPILADOR SE DESECHAN AQUI

#PUERTO DE ESCUCHA.INSTRUCCION INFORMATIVA
EXPOSE 8085
#VARIABLE DE ENTRNO QUE LEE EL FRAMEWORK DE .NET AL ARRANCAR.LE ORDENA A KESTREL(SERV WEB INTERNO DE .NET)
#QUE CONFIGURE Y ESCUCHE PETICIONES EN 8085
ENV ASPNETCORE_URLS=http://+:8085

ENTRYPOINT ["dotnet", "DevOpsDemo.dll"]




